export const productsData = [
  {
    id: 1,
    name: "Henkelion Adjustable Weighted Vest",
    description:
      "Henkelion Weighted Vest Weight Vest for Men Women Kids Weights Included, Body Weight Vests Adjustable for Running, Training Workout, Jogging, Walking",
    price: 29.99,
    rating: 4,
    reviews: 8166,
    image: "https://m.media-amazon.com/images/I/719IqROWz0L._AC_SX466_.jpg",
    featured: true,
    images: [
      "https://m.media-amazon.com/images/I/61bEle2Z2mL._AC_SX466_.jpg",
      "https://m.media-amazon.com/images/I/71bsQpYFbHL._AC_SX466_.jpg",
      "https://m.media-amazon.com/images/I/719IqROWz0L._AC_SX466_.jpg",
      "https://m.media-amazon.com/images/I/61POZLbECcL._AC_SX466_.jpg",
      "https://m.media-amazon.com/images/I/61lRe4eaAjL._AC_SX466_.jpg",
      "https://m.media-amazon.com/images/I/71qwXZPOb8L._AC_SX466_.jpg",
      "https://m.media-amazon.com/images/I/71CGbK9g7yL._AC_SX466_.jpg",
      "https://m.media-amazon.com/images/I/71tAyGZppNL._AC_SX466_.jpg",
    ],
    variants: [
      { id: "color-black", name: "Black", value: "Black", imageIndex: 0 },
      { id: "color-grey", name: "Grey", value: "Grey", imageIndex: 1 },
      { id: "color-blue", name: "Blue", value: "Blue", imageIndex: 2 },
      { id: "color-pink", name: "Pink", value: "Pink", imageIndex: 6 },
      { id: "color-purple", name: "Purple", value: "Purple", imageIndex: 7 },
    ],
    amazonUrl: "https://amzn.to/43z8XH6",
  },
  {
    id: 2,
    name: "COSORI Pressure Cooker",
    description:
      "COSORI Pressure Cooker 6QT, Stainless Steel, 9-in-1 Multi Cooker, 12 Safety Features, Ceramic Inner Pot, Rice, Slow Cook, Sous Vide, Saute, 1100W",
    price: 80.96,
    rating: 5,
    reviews: 5742,
    image: "https://m.media-amazon.com/images/I/71F4fibi-6L._AC_SX679_.jpg",
    featured: true,
    images: [
      "https://m.media-amazon.com/images/I/71F4fibi-6L._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71MG5yU0pHL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71PC+2HhvYL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61eCVrUDLKL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/81HJn8HRlYL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71r-WGapIGL._AC_SX679_.jpg",
    ],
    variants: [
      { id: "color-black", name: "Black", value: "Black", imageIndex: 0 },
    ],
    amazonUrl: "https://amzn.to/3X2ViV2",
  },
  {
    id: 3,
    name: "Meta Quest 3S Bundle",
    description:
      "Meta Quest 3S 256GB | Batman: Arkham Shadow Included — 30+ Games Included with Meta Horizon+ Access with Starter Bundles — Play More for Less",
    price: 397.29,
    rating: 5,
    reviews: 1290,
    image: "https://m.media-amazon.com/images/I/71gb4tfAUCL._SX522_.jpg",
    featured: true,
    images: [
      "https://m.media-amazon.com/images/I/71gb4tfAUCL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/719QH+HcyGL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/71F-Ubpr9-L._SX522_.jpg",
      "https://m.media-amazon.com/images/I/61Nvzguv7cL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/71OBoTHDurL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/61Gg6zKZARL._SX522_.jpg",
    ],
    variants: [
      { id: "length-128GB", name: "128GB", value: "128GB", imageIndex: 0 },
      { id: "length-256GB", name: "256GB", value: "256GB", imageIndex: 0 },
    ],
    amazonUrl: "https://amzn.to/47qZ9A3",
  },
  {
    id: 4,
    name: "Shark Vacuum Cleaner NV360",
    description:
      "Shark Upright Vacuum, Navigator Lift-Away Deluxe with Large Dust Cup Capacity, HEPA Filter, Swivel Steering, Upholstery Tool & Crevice Tool, Blue, NV360",
    price: 119.99,
    rating: 4,
    reviews: 117912,
    image: "https://m.media-amazon.com/images/I/81gGNXSjASL._AC_SL1500_.jpg",
    featured: true,
    images: [
      "https://m.media-amazon.com/images/I/81gGNXSjASL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71ybuaqVLwL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/81HtQ0vn+1L._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/91xhx2xTQ+L._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/91Iz2VWBRvL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/91vmL+HS91L._AC_SX679_.jpg",
    ],
    variants: [
      { id: "navigator-navy", name: "Navy", value: "Navy", imageIndex: 0 },
      {
        id: "navigator-lavender",
        name: "Lavender",
        value: "Lavender",
        imageIndex: 0,
      },
      { id: "navigator-white", name: "White", value: "White", imageIndex: 0 },
    ],
    amazonUrl: "https://amzn.to/47sc6tw",
  },
  {
    id: 5,
    name: "Jack ＆ Rose Travel Steamer",
    description:
      "Jack ＆ Rose Travel Steamer for Clothes,100-220V Portable Iron,15s Heat Up,Steamer ＆ Iron 2 In 1, Travel Size,Large Ceramic Heat Panel,for Global ＆ Europe",
    price: 52.24,
    rating: 5,
    reviews: 2227,
    image: "https://m.media-amazon.com/images/I/819ojrDDySL._AC_SX679_.jpg",
    featured: true,
    images: [
      "https://m.media-amazon.com/images/I/819ojrDDySL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71R43OwhG7L._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61hu5QIjdBL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71m9g3clNdL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/610aNH29Y-L._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71RckwKT6yL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/614Nz-IF7rL._AC_SX679_.jpg",
    ],
    variants: [
      { id: "color-black", name: "Black", value: "Black", imageIndex: 5 },
      { id: "color-green", name: "Green", value: "Green", imageIndex: 6 },
      { id: "color-purple", name: "Purple", value: "Purple", imageIndex: 1 },
    ],
    amazonUrl: "https://amzn.to/3JrVKZZ",
  },
]
